var variables = {
    "Weapons" : {
        "none" : 0,
        "Cleaver" : 1,
        "Dagger" : 1,
        "Quarterstaff" : 1,
        "Rock" : 1,
        "Short Sword" : 1,
        "Smoke Bomb" : 1,
        "Training Sword" : 1,
        "Wooden Mallet" : 1,
        "Arming Sword" : 2,
        "Axe" : 2,
        "Blacksmith Hammer" : 2,
        "Fire Bomb" : 2,
        "Heater Shield" : 2,
        "Targe" : 2,
        "Throwing Axe" : 2,
        "Throwing Knife" : 2,
        "Warhammer" : 2,
        "Buckler" : 3,
        "Falchion" : 3,
        "Heavy Handaxe" : 3,
        "Javelin" : 3,
        "Kite Shield" : 3,
        "Bastard Sword" : 4,
        "Mace" : 4,
        "Rapier" : 4,
        "Short Spear" : 4,
        "Billhook" : 5,
        "Longsword" : 5,
        "Messer" : 5,
        "War Axe" : 5,
        "Battle Axe" : 6,
        "Estoc" : 6,
        "Pole Axe" : 6,
        "Crossbow" : 7,
        "Executioner's Sword" : 7,
        "Greatsword" : 7,
        "Maul" : 7,
        "Recurve Bow" : 7,
        "Bardiche" : 8,
        "Eveningstar" : 8,
        "Carving Knife" : 9,
        "Pitchfork" : 9,
        "Frying Pan" : 10,
        "Heavy Branch" : 10,
        "Sickle" : 10,
        "Spear" : 10,
        "Wooden Shovel" : 10,
        "Zweihander" : 10,
        "Halberd" : 11,
        "Longbow" : 11,
        "Rake" : 11,
        "Hoe" : 12,
        "Rusty Fork" : 12,
        "Rusty Shovel" : 12,
        "Club" : 13,
        "Rusty Shovel" : 13,
        "Scythe" : 13,
        "Pickaxe" : 14,
        "Sledgehammer" : 14
    },
    "Armor" : {
        "none" : 0,
        "light" : 1,
        "medium" : 2,
        "heavy" :3
    },
    "Perks" : {
        "Acrobat" : 1,
        "Cat" : 1,
        "Fireproof" : 1,
        "Friendly" : 1,
        "Scavenger" : 1,
        "Smith" : 1,
        "Tenacious" : 1,
        "Wrecker" : 1,
        "Brawler" : 2,
        "Flesh Wound" : 2,
        "Fury" : 2,
        "Huntsman" : 2,
        "Ranger" : 2,
        "Rat" : 2,
        "Second Wind" : 2,
        "Rush" : 3,
        "Dodge" : 4,
        "Bloodlust" : 5
    }
}